# Processamento com múltiplas condições de saída
while condicao_principal:
    # Processamento...
    if situacao_especial_1:
        # Tratamento especial...
        continue
    if situacao_especial_2:
        # Outro tratamento...
        break